apiVersion: v1
kind: Service
metadata:
  name: novafleet-service
  namespace: novafleet-staging
  labels:
    app: novafleet
spec:
  type: ClusterIP
  selector:
    app: novafleet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
